Removing deprecation warnings
quiqueporta/simple-value-object pull request #5
Opened 2019-01-31 13:06 UTC by hugoleodev

Change from inspect.getargspec() to inspect.getfullargspec() to remove deprecation warnings

2019-02-11 09:27 UTC, quiqueporta commented
Do you have any example to test it?

2019-02-12 12:45 UTC, hugoleodev commented
@quiqueporta When you use getargspec on python 3, the following warning will appear 
 
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()

In my case I use your project with python 3

2019-02-14 13:39 UTC, quiqueporta commented
Ok, I will create another release with this change
Thanks :wink:

2019-02-14 13:42 UTC, quiqueporta requested changes

2019-02-14 13:42 UTC, quiqueporta commented on simple_value_object/value_object.py
> +                self.argspec = inspect.getargspec(method)
Can you define **argspec**, and **varkw** private?

2019-04-30 22:27 UTC, quiqueporta approved these changes

2019-04-30 22:30 UTC, merged